image: python:3.7

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Lint
  - Test

linting:
  stage: Lint
  script:
     pylint *.py  

unittest:
  stage: Test
  script:
    - python -m pytest *.py